#!/bin/sh

set -e

SELF="$(readlink -f "$0" 2>/dev/null || echo "$0")"
APP_DIR="$(dirname "$(dirname "$SELF")")"
DATA_DIR="/var/lib/webosbrew/gif-playlist"
ITEMS_DIR="$DATA_DIR/items"
BACKUP_DIR="$DATA_DIR/disabled-hooks"
PLAYLIST_FILE="$DATA_DIR/playlist.txt"
SETTINGS_FILE="$DATA_DIR/settings.conf"
RUNTIME_QML="$DATA_DIR/screensaver-runtime.qml"
INIT_DIR="/var/lib/webosbrew/init.d"
INIT_LINK="$INIT_DIR/55-gif-playlist"

SCREENSAVER_BASE="/usr/palm/applications/com.webos.app.screensaver"
MAIN_TARGET="$SCREENSAVER_BASE/qml/main.qml"
CLOCK_TARGET="$SCREENSAVER_BASE/qml/UserInterfaceLayer/Containers/Clock.qml"
MAX_ITEMS=12
MAX_BYTES=26214400

ensure_data() {
    mkdir -p "$ITEMS_DIR" "$BACKUP_DIR"
    [ -f "$PLAYLIST_FILE" ] || : > "$PLAYLIST_FILE"
    if [ ! -f "$SETTINGS_FILE" ]; then
        cat > "$SETTINGS_FILE" <<'EOF'
mode=ordered
duration=30000
fit=crop
EOF
    fi
}

read_setting() {
    key="$1"
    fallback="$2"
    value="$(sed -n "s/^${key}=//p" "$SETTINGS_FILE" 2>/dev/null | head -n 1)"
    [ -n "$value" ] && printf '%s' "$value" || printf '%s' "$fallback"
}

write_settings() {
    mode="$1"
    duration="$2"
    fit="$3"
    tmp="$SETTINGS_FILE.tmp.$$"
    {
        printf 'mode=%s\n' "$mode"
        printf 'duration=%s\n' "$duration"
        printf 'fit=%s\n' "$fit"
    } > "$tmp"
    mv "$tmp" "$SETTINGS_FILE"
}

valid_name() {
    case "$1" in
        ''|*[!A-Za-z0-9._-]*) return 1 ;;
        *) return 0 ;;
    esac
}

playlist_count() {
    grep -c '^[A-Za-z0-9._-][A-Za-z0-9._-]*$' "$PLAYLIST_FILE" 2>/dev/null || true
}

detect_target() {
    # webOS 3/4/5-8 use main.qml. Newer layouts may use Clock.qml.
    if [ -f "$MAIN_TARGET" ]; then
        printf '%s' "$MAIN_TARGET"
    elif [ -f "$CLOCK_TARGET" ]; then
        printf '%s' "$CLOCK_TARGET"
    else
        return 1
    fi
}

generate_qml() {
    ensure_data
    mode="$(read_setting mode ordered)"
    duration="$(read_setting duration 30000)"
    fit="$(read_setting fit crop)"

    case "$mode" in shuffle) shuffle=true ;; *) shuffle=false ;; esac
    case "$duration" in ''|*[!0-9]*) duration=30000 ;; esac
    case "$fit" in
        fit) fill_mode="Image.PreserveAspectFit" ;;
        stretch) fill_mode="Image.Stretch" ;;
        *) fill_mode="Image.PreserveAspectCrop" ;;
    esac

    tmp="$RUNTIME_QML.tmp.$$"
    cat > "$tmp" <<EOF
// Generated by GIF Playlist. Manual edits will be overwritten.
import QtQuick 2.4
import Eos.Window 0.1
import QtQuick.Window 2.2

WebOSWindow {
    id: window
    width: 1920
    height: 1080
    windowType: "_WEBOS_WINDOW_TYPE_SCREENSAVER"
    appId: "com.webos.app.screensaver"
    title: "GIF Playlist Screensaver"
    color: "black"
    visible: true

    property var playlist: [
EOF

    while IFS= read -r name; do
        valid_name "$name" || continue
        [ -f "$ITEMS_DIR/$name" ] || continue
        printf '        "file://%s/%s",\n' "$ITEMS_DIR" "$name" >> "$tmp"
    done < "$PLAYLIST_FILE"

    cat >> "$tmp" <<EOF
    ]
    property int currentIndex: 0
    property bool shuffleEnabled: $shuffle
    property int displayDuration: $duration

    function advance() {
        if (playlist.length < 2) return;
        var nextIndex;
        if (shuffleEnabled) {
            nextIndex = currentIndex;
            while (nextIndex === currentIndex) {
                nextIndex = Math.floor(Math.random() * playlist.length);
            }
        } else {
            nextIndex = (currentIndex + 1) % playlist.length;
        }
        currentIndex = nextIndex;
        rotation.restart();
    }

    Rectangle {
        anchors.fill: parent
        color: "black"
    }

    AnimatedImage {
        id: animation
        anchors.fill: parent
        source: window.playlist.length > 0 ? window.playlist[window.currentIndex] : ""
        fillMode: $fill_mode
        cache: false
        smooth: false
        playing: true

        onStatusChanged: {
            if (status === Image.Error && window.playlist.length > 1) {
                errorAdvance.restart();
            }
        }
    }

    Text {
        anchors.centerIn: parent
        visible: window.playlist.length === 0
        color: "#888888"
        font.pixelSize: 42
        text: "GIF Playlist is empty"
    }

    Timer {
        id: rotation
        interval: window.displayDuration
        running: window.playlist.length > 1
        repeat: true
        onTriggered: window.advance()
    }

    Timer {
        id: errorAdvance
        interval: 2000
        repeat: false
        onTriggered: window.advance()
    }
}
EOF

    mv "$tmp" "$RUNTIME_QML"
}

backup_conflicting_hooks() {
    mkdir -p "$BACKUP_DIR"
    for hook in "$INIT_DIR/50-idlegif" "$INIT_DIR/50-custom-screensaver"; do
        if [ -e "$hook" ] || [ -L "$hook" ]; then
            base="$(basename "$hook")"
            [ -e "$BACKUP_DIR/$base" ] || mv "$hook" "$BACKUP_DIR/$base"
        fi
    done
}

restore_conflicting_hooks() {
    for backup in "$BACKUP_DIR"/*; do
        [ -e "$backup" ] || [ -L "$backup" ] || continue
        base="$(basename "$backup")"
        destination="$INIT_DIR/$base"
        if [ ! -e "$destination" ] && [ ! -L "$destination" ]; then
            mv "$backup" "$destination"
        fi
    done
}

disable_mounts() {
    for target in "$MAIN_TARGET" "$CLOCK_TARGET"; do
        if [ -f "$target" ]; then
            umount "$target" 2>/dev/null || true
        fi
    done
}

enable_playlist() {
    ensure_data
    generate_qml
    target="$(detect_target)" || {
        echo "ERROR: no supported webOS screensaver target found" >&2
        exit 1
    }
    mkdir -p "$INIT_DIR"
    backup_conflicting_hooks
    disable_mounts
    mount --bind "$RUNTIME_QML" "$target"
    ln -sf "$APP_DIR/assets/install.sh" "$INIT_LINK"
    echo "enabled=$target"
}

add_url() {
    ensure_data
    [ "$(playlist_count)" -lt "$MAX_ITEMS" ] || {
        echo "ERROR: playlist limit is $MAX_ITEMS GIFs" >&2
        exit 1
    }

    encoded="${1:-}"
    [ -n "$encoded" ] || { echo "ERROR: missing URL" >&2; exit 1; }
    url="$(printf '%s' "$encoded" | base64 -d 2>/dev/null || true)"
    case "$url" in
        http://*|https://*) ;;
        *) echo "ERROR: only direct http/https GIF URLs are allowed" >&2; exit 1 ;;
    esac

    id="gif-$(date +%s)-$$.gif"
    tmp="$ITEMS_DIR/$id.part"
    dest="$ITEMS_DIR/$id"
    rm -f "$tmp"

    wget -q -O "$tmp" "$url" || {
        rm -f "$tmp"
        echo "ERROR: download failed" >&2
        exit 1
    }

    bytes="$(wc -c < "$tmp" | tr -d ' ')"
    case "$bytes" in ''|*[!0-9]*) bytes=0 ;; esac
    if [ "$bytes" -le 0 ] || [ "$bytes" -gt "$MAX_BYTES" ]; then
        rm -f "$tmp"
        echo "ERROR: GIF must be between 1 byte and 25 MiB" >&2
        exit 1
    fi

    signature="$(dd if="$tmp" bs=1 count=6 2>/dev/null || true)"
    case "$signature" in
        GIF87a|GIF89a) ;;
        *) rm -f "$tmp"; echo "ERROR: downloaded file is not a GIF" >&2; exit 1 ;;
    esac

    mv "$tmp" "$dest"
    printf '%s\n' "$id" >> "$PLAYLIST_FILE"
    generate_qml
    echo "added=$id"
}

remove_item() {
    ensure_data
    id="${1:-}"
    valid_name "$id" || { echo "ERROR: invalid item id" >&2; exit 1; }
    tmp="$PLAYLIST_FILE.tmp.$$"
    grep -Fvx "$id" "$PLAYLIST_FILE" > "$tmp" || true
    mv "$tmp" "$PLAYLIST_FILE"
    rm -f "$ITEMS_DIR/$id"
    generate_qml
    echo "removed=$id"
}

move_item() {
    ensure_data
    id="${1:-}"
    direction="${2:-}"
    valid_name "$id" || { echo "ERROR: invalid item id" >&2; exit 1; }
    case "$direction" in up|down) ;; *) echo "ERROR: direction must be up or down" >&2; exit 1 ;; esac

    tmp="$PLAYLIST_FILE.tmp.$$"
    awk -v wanted="$id" -v direction="$direction" '
        { lines[NR] = $0; if ($0 == wanted) position = NR }
        END {
            count = NR
            if (direction == "up" && position > 1) {
                swap = lines[position - 1]; lines[position - 1] = lines[position]; lines[position] = swap
            } else if (direction == "down" && position > 0 && position < count) {
                swap = lines[position + 1]; lines[position + 1] = lines[position]; lines[position] = swap
            }
            for (i = 1; i <= count; i++) print lines[i]
        }
    ' "$PLAYLIST_FILE" > "$tmp"
    mv "$tmp" "$PLAYLIST_FILE"
    generate_qml
    echo "moved=$id:$direction"
}

set_option() {
    ensure_data
    key="${1:-}"
    value="${2:-}"
    mode="$(read_setting mode ordered)"
    duration="$(read_setting duration 30000)"
    fit="$(read_setting fit crop)"

    case "$key" in
        mode)
            case "$value" in ordered|shuffle) mode="$value" ;; *) echo "ERROR: invalid mode" >&2; exit 1 ;; esac
            ;;
        duration)
            case "$value" in ''|*[!0-9]*) echo "ERROR: invalid duration" >&2; exit 1 ;; esac
            [ "$value" -ge 5000 ] && [ "$value" -le 300000 ] || { echo "ERROR: duration must be 5000-300000 ms" >&2; exit 1; }
            duration="$value"
            ;;
        fit)
            case "$value" in crop|fit|stretch) fit="$value" ;; *) echo "ERROR: invalid fit mode" >&2; exit 1 ;; esac
            ;;
        *) echo "ERROR: unknown setting" >&2; exit 1 ;;
    esac

    write_settings "$mode" "$duration" "$fit"
    generate_qml
    echo "updated=$key:$value"
}

list_items() {
    ensure_data
    while IFS= read -r id; do
        valid_name "$id" || continue
        [ -f "$ITEMS_DIR/$id" ] || continue
        bytes="$(wc -c < "$ITEMS_DIR/$id" | tr -d ' ')"
        printf '%s\t%s\n' "$id" "$bytes"
    done < "$PLAYLIST_FILE"
}

show_status() {
    ensure_data
    target="$(detect_target 2>/dev/null || true)"
    enabled=no
    if [ -n "$target" ] && findmnt "$target" 2>/dev/null | grep -F "$RUNTIME_QML" >/dev/null 2>&1; then
        enabled=yes
    fi
    printf 'enabled=%s\n' "$enabled"
    printf 'target=%s\n' "$target"
    printf 'count=%s\n' "$(playlist_count)"
    printf 'mode=%s\n' "$(read_setting mode ordered)"
    printf 'duration=%s\n' "$(read_setting duration 30000)"
    printf 'fit=%s\n' "$(read_setting fit crop)"
}

uninstall_override() {
    disable_mounts
    rm -f "$INIT_LINK"
    restore_conflicting_hooks
    echo "override removed; playlist data preserved"
}

reset_all() {
    uninstall_override
    rm -rf "$DATA_DIR"
    echo "playlist data removed"
}

command="${1:-status}"
case "$command" in
    init) ensure_data; generate_qml; show_status ;;
    status) show_status ;;
    list) list_items ;;
    add) add_url "${2:-}" ;;
    remove) remove_item "${2:-}" ;;
    move) move_item "${2:-}" "${3:-}" ;;
    set) set_option "${2:-}" "${3:-}" ;;
    generate) generate_qml ;;
    enable) enable_playlist ;;
    disable) disable_mounts; rm -f "$INIT_LINK"; echo "disabled" ;;
    uninstall) uninstall_override ;;
    reset) reset_all ;;
    *) echo "ERROR: unknown command: $command" >&2; exit 1 ;;
esac
